#pragma once

#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD_PER_KEY

#define CAPS_WORD_IDLE_TIMEOUT 750
#define FLOW_TAP_TERM 200

#define MOUSEKEY_INERTIA
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 7
#define MOUSEKEY_MAX_SPEED 12
#define MOUSEKEY_TIME_TO_MAX 36
#define MOUSEKEY_FRICTION 70

#define RGBLIGHT_DEFAULT_ON false
